# Generated by Django 4.2.9 on 2024-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('commodity_name', models.CharField(max_length=100)),
                ('buy_vol', models.IntegerField()),
                ('price', models.FloatField()),
                ('buyer_id', models.IntegerField()),
                ('order_type', models.CharField(max_length=100)),
                ('is_done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FragmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=100)),
                ('sell_order_id', models.IntegerField()),
                ('buy_order_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('sold_price', models.FloatField()),
                ('sold_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('commodity_name', models.CharField(max_length=100)),
                ('sell_vol', models.IntegerField()),
                ('price', models.FloatField()),
                ('seller_id', models.IntegerField()),
                ('order_type', models.CharField(max_length=100)),
                ('is_done', models.BooleanField()),
            ],
        ),
    ]
